export const initialAnnotations = [
  {
    id: "R6valD",
    width: 279,
    height: 49,
    x: 528,
    y: 113,
    label: "InvoiceNumber",
    value: "54212825",
    section: "InvoiceDetails",
    // version: 'version1'
  },
  {
    id: "DJya8F",
    width: 265,
    height: 49,
    x: 1204,
    y: 215,
    label: "InvoiceDate",
    value: "05/01/2015",
    section: "InvoiceDetails",
    // version: 'version2'
  },
  {
    id: "TXK1xE",
    width: 333,
    height: 49,
    x: 210,
    y: 760,
    label: "SellerName",
    value: "Hutchinson PLC",
    section: "SellerDetails",
    // version: 'version3'
  },
  {
    id: "ZXYJPY",
    width: 451,
    height: 101,
    x: 213,
    y: 818,
    label: "SellerAddress",
    value: "7046 Barrett Mount\nFloresberg, AZ 86083",
    section: "SellerDetails",
  },
  {
    id: "4QyGWX",
    width: 275,
    height: 49,
    x: 365,
    y: 972,
    label: "SellerTaxNumber",
    value: "959-74-2014",
    section: "SellerDetails",
  },
  {
    id: "rt63t4",
    width: 319,
    height: 49,
    x: 1252,
    y: 763,
    label: "ClientName",
    value: "Chapman-Long",
    section: "BuyerDetails",
  },
  {
    id: "zvOpHg",
    width: 500,
    height: 53,
    x: 1247,
    y: 811,
    label: "ClientAddress",
    value: "245 Eric Rest Suite 622\nPort Jimmyview, CO 68684",
    section: "BuyerDetails",
  },
  {
    id: "c9ju2Y",
    width: 270,
    height: 39,
    x: 1407,
    y: 979,
    label: "ClientTaxNumber",
    value: "953-85-0282",
    section: "BuyerDetails",
  },
  {
    id: "8MoRBg",
    width: 483,
    height: 42,
    x: 361,
    y: 1483,
    label: "Description",
    value:
      "Alcoholmeter Alcohol Meter Wine 0-100%+Thermometer Set Bar Tools Vintage Tester",
    section: "ItemDetails",
    product: 1,
  },
  {
    id: "BxB0bw",
    width: 86,
    height: 52,
    x: 1007,
    y: 1394,
    label: "Qty",
    value: "3.00",
    section: "ItemDetails",
    product: 1,
  },
  {
    id: "awk6v5",
    width: 88,
    height: 42,
    x: 1155,
    y: 1397,
    label: "UnitOfMeasure",
    value: "each",
    section: "ItemDetails",
    product: 1,
  },
  {
    id: "Lsywn7",
    width: 102,
    height: 38,
    x: 1427,
    y: 1401,
    label: "NetPrice",
    value: "14.08",
    section: "ItemDetails",
    product: 1,
  },
  {
    id: "NS4lKL",
    width: 84,
    height: 42,
    x: 1918,
    y: 1397,
    label: "Tax",
    value: "10%",
    section: "ItemDetails",
    product: 1,
  },
  {
    id: "rR0ign",
    width: 103,
    height: 38,
    x: 2151,
    y: 1401,
    label: "Total_for_each_item",
    value: "46.46",
    section: "ItemDetails",
    product: 1,
  },
  {
    id: "yvCupx",
    width: 478,
    height: 42,
    x: 358,
    y: 1572,
    label: "Description",
    value: "Vintage Wine Basket Holder - 3 Bottles",
    section: "ItemDetails",
    product: 2,
  },
  {
    id: "E9C3Hx",
    width: 81,
    height: 42,
    x: 1010,
    y: 1572,
    label: "Qty",
    value: "2.00",
    section: "ItemDetails",
    product: 2,
  },
  {
    id: "UTtDrP",
    width: 88,
    height: 39,
    x: 1155,
    y: 1572,
    label: "UnitOfMeasure",
    value: "each",
    section: "ItemDetails",
    product: 2,
  },
  {
    id: "eAmwb5",
    width: 81,
    height: 42,
    x: 1446,
    y: 1702,
    label: "NetPrice",
    value: "3.99",
    section: "ItemDetails",
    product: 2,
  },
  {
    id: "dnHxuI",
    width: 84,
    height: 39,
    x: 1918,
    y: 1572,
    label: "Tax",
    value: "10%",
    section: "ItemDetails",
    product: 2,
  },
  {
    id: "RQTXU2",
    width: 81,
    height: 42,
    x: 2173,
    y: 1702,
    label: "Total_for_each_item",
    value: "8.78",
    section: "ItemDetails",
    product: 2,
  },
  {
    id: "E9PArD",
    width: 522,
    height: 87,
    x: 356,
    y: 1702,
    label: "Description",
    value: "Wagner Vineyards uncork new york Wine Glass",
    section: "ItemDetails",
    product: 3,
  },
  {
    id: "IpurAc",
    width: 81,
    height: 42,
    x: 1010,
    y: 1832,
    label: "Qty",
    value: "1.00",
    section: "ItemDetails",
    product: 3,
  },
  {
    id: "K9rtfi",
    width: 88,
    height: 42,
    x: 1155,
    y: 1702,
    label: "UnitOfMeasure",
    value: "each",
    section: "ItemDetails",
    product: 3,
  },
  {
    id: "UdQuz7",
    width: 122,
    height: 38,
    x: 1405,
    y: 1836,
    label: "NetPrice",
    value: "279.00",
    section: "ItemDetails",
    product: 3,
  },
  {
    id: "x6WFiV",
    width: 84,
    height: 42,
    x: 1918,
    y: 1702,
    label: "Tax",
    value: "10%",
    section: "ItemDetails",
    product: 3,
  },
  {
    id: "qzNdQM",
    width: 122,
    height: 42,
    x: 2132,
    y: 1832,
    label: "Total_for_each_item",
    value: "306.90",
    section: "ItemDetails",
    product: 3,
  },
  {
    id: "Jfpls6",
    width: 483,
    height: 128,
    x: 358,
    y: 1832,
    label: "Description",
    value:
      "Press Wine 15L Fruit Cider Apple Crusher Juice Grape Stainless Maker Grapes New",
    section: "ItemDetails",
    product: 4,
  },
  {
    id: "u6oX92",
    width: 88,
    height: 42,
    x: 1155,
    y: 1832,
    label: "UnitOfMeasure",
    value: "each",
    section: "ItemDetails",
    product: 4,
  },
  {
    id: "BSGyU4",
    width: 124,
    height: 42,
    x: 1657,
    y: 1832,
    label: "NetPrice",
    value: "279.00",
    section: "ItemDetails",
    product: 4,
  },
  {
    id: "BFVEM3",
    width: 84,
    height: 42,
    x: 1918,
    y: 1832,
    label: "Tax",
    value: "10%",
    section: "ItemDetails",
    product: 4,
  },
  {
    id: "QFyHRL",
    width: 471,
    height: 127,
    x: 358,
    y: 2045,
    label: "Description",
    value:
      "100pcs Heat Shrink Capsules PvC Wine Bottle Caps Shrinkable Seal Film Covers 3cm",
    section: "ItemDetails",
    product: 5,
  },
  {
    id: "Ks6t4g",
    width: 84,
    height: 39,
    x: 1007,
    y: 2007,
    label: "Qty",
    value: "4.00",
    section: "ItemDetails",
    product: 5,
  },
  {
    id: "4Mn2GB",
    width: 88,
    height: 42,
    x: 1155,
    y: 2004,
    label: "UnitOfMeasure",
    value: "each",
    section: "ItemDetails",
    product: 5,
  },
  {
    id: "UWJFrh",
    width: 81,
    height: 42,
    x: 1446,
    y: 2004,
    label: "NetPrice",
    value: "5.75",
    section: "ItemDetails",
    product: 5,
  },
  {
    id: "Kgxb2y",
    width: 84,
    height: 42,
    x: 1918,
    y: 2004,
    label: "Tax",
    value: "10%",
    section: "ItemDetails",
    product: 5,
  },
  {
    id: "2ZeDf0",
    width: 103,
    height: 42,
    x: 2151,
    y: 2004,
    label: "Total_for_each_item",
    value: "25.30",
    section: "ItemDetails",
    product: 5,
  },
  {
    id: "No7Qx9",
    width: 546,
    height: 128,
    x: 356,
    y: 2219,
    label: "Description",
    value:
      "Cuisinart Stainless Steel Electric Wine Opener - CWO-25 - Brand New in the Box",
    section: "ItemDetails",
    product: 6,
  },
  {
    id: "zbhMuy",
    width: 84,
    height: 43,
    x: 1007,
    y: 2219,
    label: "Qty",
    value: "4.00",
    section: "ItemDetails",
    product: 6,
  },
  {
    id: "DqRPS3",
    width: 88,
    height: 43,
    x: 1155,
    y: 2219,
    label: "UnitOfMeasure",
    value: "each",
    section: "ItemDetails",
    product: 6,
  },
  {
    id: "hxE0Yq",
    width: 102,
    height: 43,
    x: 1427,
    y: 2219,
    label: "NetPrice",
    value: "19.90",
    section: "ItemDetails",
    product: 6,
  },
  {
    id: "pTtp1W",
    width: 84,
    height: 43,
    x: 1918,
    y: 2219,
    label: "Tax",
    value: "10%",
    section: "ItemDetails",
    product: 6,
  },
  {
    id: "fmbhry",
    width: 103,
    height: 43,
    x: 2151,
    y: 2219,
    label: "Total_for_each_item",
    value: "87.56",
    section: "ItemDetails",
    product: 6,
  },
  {
    id: "2XhfWS",
    width: 495,
    height: 165,
    x: 356,
    y: 2391,
    label: "Description",
    value:
      "Stainless Steel Reusable Vacuum Sealed Champagne Red Wine Bottle Stopper Cap New",
    section: "ItemDetails",
    product: 7,
  },
  {
    id: "Z9NvJl",
    width: 86,
    height: 53,
    x: 1007,
    y: 2387,
    label: "Qty",
    value: "3.00",
    section: "ItemDetails",
    product: 7,
  },
  {
    id: "c8P32M",
    width: 88,
    height: 42,
    x: 1155,
    y: 2391,
    label: "UnitOfMeasure",
    value: "each",
    section: "ItemDetails",
    product: 7,
  },
  {
    id: "dGyoDf",
    width: 83,
    height: 42,
    x: 1446,
    y: 2391,
    label: "NetPrice",
    value: "1.20",
    section: "ItemDetails",
    product: 7,
  },
  {
    id: "WAx0Ei",
    width: 84,
    height: 42,
    x: 1918,
    y: 2391,
    label: "Tax",
    value: "10%",
    section: "ItemDetails",
    product: 7,
  },
  {
    id: "w1mypf",
    width: 81,
    height: 42,
    x: 2173,
    y: 2391,
    label: "Total_for_each_item",
    value: "3.96",
    section: "ItemDetails",
    product: 7,
  },
  {
    id: "iRTg8R",
    width: 604,
    height: 49,
    x: 339,
    y: 1031,
    label: "IBAN",
    value: "GB39WGXI06397307045703",
    section: "BankDetails",
  },
  {
    id: "MCpF1G",
    width: 124,
    height: 42,
    x: 1463,
    y: 2870,
    label: "TotalTaxableAmount",
    value: "$501.40",
    section: "InvoiceSummary",
  },
  {
    id: "unaSZZ",
    width: 103,
    height: 42,
    x: 1761,
    y: 2870,
    label: "TotalTaxesAmount",
    value: "$50.14",
    section: "InvoiceSummary",
  },
];

export const pdfData = [
  {
    "id": "GK4oDO",
    "width": 279,
    "height": 49,
    "x": 528,
    "y": 113,
    "label": "InvoiceNumber",
    "value": "61356291",
    "section": "InvoiceDetails",
    "short_desc": "Invoice No."
  },
  {
    "id": "AQW0dz",
    "width": 267,
    "height": 49,
    "x": 1204,
    "y": 215,
    "label": "InvoiceDate",
    "value": "09/06/2012",
    "section": "InvoiceDetails",
    "short_desc": "Invoice Date"
  },
  {
    "id": "aUZr8u",
    "width": 539,
    "height": 55,
    "x": 213,
    "y": 757,
    "label": "SellerName",
    "value": "Chapman, Kim and Green",
    "section": "SellerDetails",
    "short_desc": "Supplier Name"
  },
  {
    "id": "twRLoU",
    "width": 493,
    "height": 104,
    "x": 210,
    "y": 815,
    "label": "SellerAddress",
    "value": "64731 James Branch\nSmithmouth, NC 26872",
    "section": "SellerDetails",
    "short_desc": "Supplier Address"
  },
  {
    "id": "Y2umVT",
    "width": 270,
    "height": 39,
    "x": 368,
    "y": 979,
    "label": "SellerTaxNumber",
    "value": "949-84-9105",
    "section": "SellerDetails",
    "short_desc": "Supplier Tax Number"
  },
  {
    "id": "EQeJis",
    "width": 396,
    "height": 49,
    "x": 1252,
    "y": 763,
    "label": "ClientName",
    "value": "Rodriguez-Stevens",
    "section": "BuyerDetails",
    "short_desc": "Customer Name"
  },
  {
    "id": "WDpqHB",
    "width": 481,
    "height": 108,
    "x": 1252,
    "y": 811,
    "label": "ClientAddress",
    "value": "2280 Angela Plain\nHortonshire, MS 93248",
    "section": "BuyerDetails",
    "short_desc": "Customer Address"
  },
  {
    "id": "4gF2MQ",
    "width": 272,
    "height": 39,
    "x": 1405,
    "y": 979,
    "label": "ClientTaxNumber",
    "value": "939-98-8477",
    "section": "BuyerDetails",
    "short_desc": "Customer Tax Number"
  },
  {
    "id": "bnFEsx",
    "width": 517,
    "height": 132,
    "x": 356,
    "y": 1527,
    "label": "Description",
    "value": "Wine Glasses Goblets Pair Clear Glass With Hooks Stemware Storage Multiple Uses Iron Wine Rack Hanging Glass",
    "section": "ItemDetails",
    "product": 1,
    "short_desc": "Product Description"
  },
  {
    "id": "ATtfhW",
    "width": 81,
    "height": 38,
    "x": 1010,
    "y": 1401,
    "label": "Qty",
    "value": "5.00",
    "section": "ItemDetails",
    "product": 1,
    "short_desc": "Product Quantity"
  },
  {
    "id": "6E5BFC",
    "width": 88,
    "height": 42,
    "x": 1155,
    "y": 1397,
    "label": "UnitOfMeasure",
    "value": "each",
    "section": "ItemDetails",
    "product": 1,
    "short_desc": "Product Unit Of Measure"
  },
  {
    "id": "FijkXR",
    "width": 102,
    "height": 38,
    "x": 1427,
    "y": 1401,
    "label": "NetPrice",
    "value": "12.00",
    "section": "ItemDetails",
    "product": 1,
    "short_desc": "Product net Price"
  },
  {
    "id": "Wr12Gt",
    "width": 84,
    "height": 38,
    "x": 1918,
    "y": 1401,
    "label": "Tax",
    "value": "10%",
    "section": "ItemDetails",
    "product": 1,
    "short_desc": "Product Tax Percentage"
  },
  {
    "id": "rxRibq",
    "width": 103,
    "height": 38,
    "x": 2151,
    "y": 1401,
    "label": "Total_for_each_item",
    "value": "66.00",
    "section": "ItemDetails",
    "product": 1,
    "short_desc": "Product Total"
  },
  {
    "id": "u7Dc8a",
    "width": 551,
    "height": 121,
    "x": 356,
    "y": 1702,
    "label": "Description",
    "value": "Replacement Corkscrew Parts Spiral Worm Wine Opener Bottle Houdini",
    "section": "ItemDetails",
    "product": 2,
    "short_desc": "Product Description"
  },
  {
    "id": "qx3s1l",
    "width": 81,
    "height": 42,
    "x": 1010,
    "y": 1702,
    "label": "Qty",
    "value": "1.00",
    "section": "ItemDetails",
    "product": 2,
    "short_desc": "Product Quantity"
  },
  {
    "id": "Qo3jW2",
    "width": 88,
    "height": 39,
    "x": 1155,
    "y": 1531,
    "label": "UnitOfMeasure",
    "value": "each",
    "section": "ItemDetails",
    "product": 2,
    "short_desc": "Product Unit Of Measure"
  },
  {
    "id": "5D6by2",
    "width": 83,
    "height": 42,
    "x": 1446,
    "y": 1702,
    "label": "NetPrice",
    "value": "7.50",
    "section": "ItemDetails",
    "product": 2,
    "short_desc": "Product net Price"
  },
  {
    "id": "dOaDN9",
    "width": 81,
    "height": 39,
    "x": 1921,
    "y": 1531,
    "label": "Tax",
    "value": "10%",
    "section": "ItemDetails",
    "product": 2,
    "short_desc": "Product Tax Percentage"
  },
  {
    "id": "u3Iisa",
    "width": 81,
    "height": 42,
    "x": 2173,
    "y": 1702,
    "label": "Total_for_each_item",
    "value": "8.25",
    "section": "ItemDetails",
    "product": 2,
    "short_desc": "Product Total"
  },
  {
    "id": "NK7IvE",
    "width": 519,
    "height": 132,
    "x": 356,
    "y": 1873,
    "label": "Description",
    "value": "HOME ESSENTIALS GRADIENT STEMLESS WINE GLASSES SET OF 4 20 FL OZ (591 ml) NEW",
    "section": "ItemDetails",
    "product": 3,
    "short_desc": "Product Description"
  },
  {
    "id": "ZF3Ga4",
    "width": 81,
    "height": 43,
    "x": 1010,
    "y": 1873,
    "label": "Qty",
    "value": "1.00",
    "section": "ItemDetails",
    "product": 3,
    "short_desc": "Product Quantity"
  },
  {
    "id": "xWhFPz",
    "width": 88,
    "height": 42,
    "x": 1155,
    "y": 1702,
    "label": "UnitOfMeasure",
    "value": "each",
    "section": "ItemDetails",
    "product": 3,
    "short_desc": "Product Unit Of Measure"
  },
  {
    "id": "naWQMc",
    "width": 102,
    "height": 43,
    "x": 1427,
    "y": 1873,
    "label": "NetPrice",
    "value": "12.99",
    "section": "ItemDetails",
    "product": 3,
    "short_desc": "Product net Price"
  },
  {
    "id": "znaAVe",
    "width": 84,
    "height": 42,
    "x": 1918,
    "y": 1702,
    "label": "Tax",
    "value": "10%",
    "section": "ItemDetails",
    "product": 3,
    "short_desc": "Product Tax Percentage"
  },
  {
    "id": "7Ru9F5",
    "width": 103,
    "height": 43,
    "x": 2151,
    "y": 1873,
    "label": "Total_for_each_item",
    "value": "14.29",
    "section": "ItemDetails",
    "product": 3,
    "short_desc": "Product Total"
  },
  {
    "id": "jnje44",
    "width": 587,
    "height": 49,
    "x": 339,
    "y": 1027,
    "label": "IBAN",
    "value": "GB50ACIE59715038217063",
    "section": "BankDetails",
    "short_desc": "Supplier IBAN"
  },
  {
    "id": "Ozo55H",
    "width": 120,
    "height": 42,
    "x": 1465,
    "y": 2312,
    "label": "TotalTaxableAmount",
    "value": "$192.81",
    "section": "InvoiceSummary",
    "short_desc": "Payment Amount Base"
  },
  {
    "id": "PoIJm4",
    "width": 105,
    "height": 42,
    "x": 1761,
    "y": 2312,
    "label": "TotalTaxesAmount",
    "value": "$19.28",
    "section": "InvoiceSummary",
    "short_desc": "Payment Amount Tax"
  },
  {
    "id": "ltnqc5",
    "width": 123,
    "height": 42,
    "x": 2136,
    "y": 2312,
    "label": "FinalTotal",
    "value": "$212.09",
    "section": "InvoiceSummary",
    "short_desc": "Payment Amount Total"
  }
]