export const initialAnnotations = [
  {
    id: "MHfyl8",
    width: 279,
    height: 49,
    x: 528,
    y: 113,
    label: "InvoiceNumber",
    value: "16662010",
    section: "InvoiceDetails",
  },
  {
    id: "haUYks",
    width: 267,
    height: 49,
    x: 1204,
    y: 215,
    label: "InvoiceDate",
    value: "08/28/2016",
    section: "InvoiceDetails",
  },
  {
    id: "fybWx9",
    width: 251,
    height: 49,
    x: 210,
    y: 760,
    label: "SellerName",
    value: "Smith-Cook",
    section: "SellerDetails",
  },
  {
    id: "lYpF1N",
    width: 653,
    height: 108,
    x: 210,
    y: 811,
    label: "SellerAddress",
    value: "174 Justin Causeway West Michaelmouth ME 69894",
    section: "SellerDetails",
  },
  {
    id: "R8fXYK",
    width: 270,
    height: 39,
    x: 368,
    y: 979,
    label: "SellerTaxNumber",
    value: "959-84-2124",
    section: "SellerDetails",
  },
  {
    id: "WyHcQT",
    width: 328,
    height: 49,
    x: 1252,
    y: 763,
    label: "ClientName",
    value: "Snyder-Johnson",
    section: "BuyerDetails",
  },
  {
    id: "On4LZM",
    width: 480,
    height: 108,
    x: 1250,
    y: 811,
    label: "ClientAddress",
    value: "05173 Heather Mill Jenniferfort WV 79662",
    section: "BuyerDetails",
  },
  {
    id: "KMXGQR",
    width: 272,
    height: 39,
    x: 1405,
    y: 979,
    label: "ClientTaxNumber",
    value: "938-85-4960",
    section: "BuyerDetails",
  },
  {
    id: "6qAr0R",
    width: 532,
    height: 124,
    x: 358,
    y: 1401,
    label: "Description",
    value:
      "Nintendo Gameboy Pocket Console Green with Box MGB-001 Japan Tested Working",
    section: "ItemDetails",
    product: "1",
  },
  {
    id: "EkyY28",
    width: 81,
    height: 42,
    x: 1010,
    y: 1397,
    label: "Qty",
    value: "100",
    section: "ItemDetails",
    product: "1",
  },
  {
    id: "4hbjKz",
    width: 88,
    height: 42,
    x: 1155,
    y: 1397,
    label: "UnitOfMeasure",
    value: "each",
    section: "ItemDetails",
    product: "1",
  },
  {
    id: "QC32Yw",
    width: 102,
    height: 38,
    x: 1427,
    y: 1401,
    label: "NetPrice",
    value: "6500",
    section: "ItemDetails",
    product: "1",
  },
  {
    id: "QCRQnn",
    width: 84,
    height: 42,
    x: 1918,
    y: 1397,
    label: "Tax",
    value: "10%",
    section: "ItemDetails",
    product: "1",
  },
  {
    id: "7g6ABN",
    width: 103,
    height: 38,
    x: 2151,
    y: 1401,
    label: "Total_for_each_item",
    value: "7150",
    section: "ItemDetails",
    product: "1",
  },
  {
    id: "EzMoPs",
    width: 490,
    height: 124,
    x: 358,
    y: 1610,
    label: "Description",
    value: "New Sony Playstation 4 Slim 1TB 3 Game Bundle Console Sealed!!!",
    section: "ItemDetails",
    product: "2",
  },
  {
    id: "9UmRal",
    width: 81,
    height: 42,
    x: 1010,
    y: 1613,
    label: "Qty",
    value: "300",
    section: "ItemDetails",
    product: "2",
  },
  {
    id: "UKhJ7L",
    width: 88,
    height: 42,
    x: 1155,
    y: 1613,
    label: "UnitOfMeasure",
    value: "each",
    section: "ItemDetails",
    product: "2",
  },
  {
    id: "oH4lwA",
    width: 122,
    height: 42,
    x: 1405,
    y: 1613,
    label: "NetPrice",
    value: "39999",
    section: "ItemDetails",
    product: "2",
  },
  {
    id: "gR7hRV",
    width: 84,
    height: 42,
    x: 1918,
    y: 1613,
    label: "Tax",
    value: "10%",
    section: "ItemDetails",
    product: "2",
  },
  {
    id: "UBzWGq",
    width: 534,
    height: 87,
    x: 356,
    y: 1781,
    label: "Description",
    value: "Atari Flashback 4 Classic Game Console 75 built",
    section: "ItemDetails",
    product: "3",
  },
  {
    id: "TyPKAq",
    width: 84,
    height: 42,
    x: 1007,
    y: 1784,
    label: "Qty",
    value: "400",
    section: "ItemDetails",
    product: "3",
  },
  {
    id: "Dz73kD",
    width: 88,
    height: 42,
    x: 1155,
    y: 1784,
    label: "UnitOfMeasure",
    value: "each",
    section: "ItemDetails",
    product: "3",
  },
  {
    id: "bbis4Q",
    width: 83,
    height: 42,
    x: 1446,
    y: 1784,
    label: "NetPrice",
    value: "850",
    section: "ItemDetails",
    product: "3",
  },
  {
    id: "huauHM",
    width: 84,
    height: 42,
    x: 1918,
    y: 1784,
    label: "Tax",
    value: "10%",
    section: "ItemDetails",
    product: "3",
  },
  {
    id: "0LeuZs",
    width: 103,
    height: 42,
    x: 2151,
    y: 1784,
    label: "Total_for_each_item",
    value: "3740",
    section: "ItemDetails",
    product: "3",
  },
  {
    id: "4YuBX6",
    width: 537,
    height: 86,
    x: 358,
    y: 1956,
    label: "Description",
    value: "Sony PlayStation 1 PS1 Console model scph-7501",
    section: "ItemDetails",
    product: "4",
  },
  {
    id: "zQGssg",
    width: 88,
    height: 53,
    x: 1005,
    y: 1952,
    label: "Qty",
    value: "400",
    section: "ItemDetails",
    product: "4",
  },
  {
    id: "A8uAgI",
    width: 88,
    height: 39,
    x: 1155,
    y: 1959,
    label: "UnitOfMeasure",
    value: "each",
    section: "ItemDetails",
    product: "4",
  },
  {
    id: "O1hX3E",
    width: 100,
    height: 42,
    x: 1427,
    y: 1959,
    label: "NetPrice",
    value: "1499",
    section: "ItemDetails",
    product: "4",
  },
  {
    id: "ybxwiY",
    width: 81,
    height: 42,
    x: 1921,
    y: 1956,
    label: "Tax",
    value: "10%",
    section: "ItemDetails",
    product: "4",
  },
  {
    id: "J3XvoB",
    width: 103,
    height: 42,
    x: 2151,
    y: 1959,
    label: "Total_for_each_item",
    value: "6596",
    section: "ItemDetails",
    product: "4",
  },
];
